---
title: "Schedule - Spatial Transcriptomics"
sidebar: false
toc: false
---

## Pre-reading

1. [Spatial Technology Overview](../lessons/01_spatial_technologies.qmd)
2. [Space Ranger Summary](../lessons/02_spaceranger.qmd)
3. [Download Project](https://www.dropbox.com/scl/fi/kowvbpx01iao4skuintm9/spatial_transcriptomics.zip?rlkey=ilhhec3iu9b4cdllsg0n8gitw&st=ujvl4ydc&dl=1)

## Day 1

| Time |  Topic  | Instructor |
|:-----------:|:----------:|:--------:|
| 10:00 - 10:15 | [Workshop Introduction](../slides/workshop_intro_slides.pdf) |  Will |
| 10:15 - 11:15| [Introduction to Spatial Transcriptomics](../slides/Spatial_Transcriptomics_06102026_HBC.pdf) | [Dr. Arpita Kulkarni](https://research.bidmc.org/omics/news/introducing-dr-arpita-kulkarni-co-director-functional-genomics-and-bioinformatics-core) |
| 11:15 - 11:20 | Break | |
| 11:20 - 11:55 | [Load Visium HD Data](../lessons/03_loading_spatial_data.qmd) | Noor |
| 11:55 - 12:00 | Overview of self-learning materials and homework submission | Will |

### Before the next class:

I. Please **study the contents** and **work through all the code** within the following lessons:
 
   1. [Principal Component Analysis (PCA)](../lessons/04_theory_of_PCA.qmd)
      
      :::{.callout-note collapse="true" title="Click here for a preview of this lesson"}
      This lesson introduces participants to the theory and mechanics of Principal Components Analysis (PCA). Through a step‑by‑step, hands‑on walkthrough, participants learn how to derive the covariance matrix, obtain eigenvalues and eigenvectors, compute principal component scores and compare their manual PCA results with the output of `prcomp()`.
      
      In this lesson, you will:
      
        - Derive the covariance matrix used for Principal Components Analysis
        - Explain the roles of eigenvectors and eigenvalues within a Principal Components Analysis
        - Compare and contrast our Principal Components Analysis to the output of `prcomp()`
      :::
      
   2. [Quality Control](../lessons/05_quality_control.qmd)
      
      :::{.callout-note collapse="true" title="Click here for a preview of this lesson"}
      This lesson focuses on quality control strategies for Visium HD, using thresholds on genes, UMIs and mitochondrial content to filter low-quality spots. This lesson helps you detect technical artifacts and sample issues before downstream analyses.
      
      In this lesson, you will:
      
        - Construct quality control metrics and visually evaluate the quality of the data
        - Apply appropriate filters to remove low quality cells
        - Create a filtered seurat object
      :::

II. **Submit your work**:
   * Each lesson above contains exercises; please go through each of them.
   * **Submit your answers** to the exercises using [this Google form](https://forms.gle/PFk1fcCj8phzsLb88) on **the day *before* the next class**.
   
### Questions?
* ***If you get stuck due to an error*** while running code in the lesson, [email us](mailto:hbctraining@hsph.harvard.edu) 

***

## Day 2

| Time |  Topic  | Instructor |
|:-----------:|:----------:|:--------:|
| 10:00 - 10:30 | Self-learning lessons discussion | All |
| 10:30 - 11:10 | [Normalization and Sketch Downsampling](../lessons/06_normalization_and_sketch.qmd) | Will |
| 11:10 - 11:15 | Break | |
| 11:15 - 11:55 | [Dimensionality Reduction](../lessons/07_dim_reduction.qmd) | Noor |
| 11:55 - 12:00 | Overview of self-learning materials and homework submission | Will |

### Before the next class:

I. Please **study the contents** and **work through all the code** within the following lessons:

   1. [Clustering](../lessons/08_clustering.qmd)

      :::{.callout-note collapse="true" title="Click here for a preview of this lesson"}
      This lesson will use graph-based clustering methods k-nearest neighbors and Leiden to define clusters based upon gene expression scores for single-cell datasets. You will examine how parameters like resolution affect cluster size and tissue interpretation.
      
      In this lesson, you will:
      
        - Compute a neighborhood graph to identify similar phenotypes in bins
        - Group bins into clusters based upon their gene expression profiles
        - Evaluate the quality of clustering against biological knowns
      :::

   2. [Integration](../lessons/09_integration.qmd)

      :::{.callout-note collapse="true" title="Click here for a preview of this lesson"}
      This lesson will introduce how to evaluate whether batch effects are found in your dataset which will inform the decision of whether to integrate or not. Additionally describes the methods behind some common methods for integration.

      In this lesson, you will:
      
        - Identify when integration is necessary
        - Evaluate potential batch effect in our datset
        - Compare common integration algorithms
      :::

   3. [Seurat Cheatsheet](../lessons/10_seurat_cheatsheet.qmd)

      :::{.callout-note collapse="true" title="Click here for a preview of this lesson"}
      This lesson will introduce a compact Seurat cheatsheet to keep at hand that summarizes key functions for spatial transcriptomics workflows, from data loading to clustering and plotting. Use this reference to speed up scripting, avoid common syntax errors, and standardize your analysis pipeline.
      
      In this lesson, you will:
      
        - Access various slots of the Seurat object
        - Generate a variety of plots with the plotting functions within Seurat
      :::
         
II. **Submit your work**:
   * Each lesson above contains exercises; please go through each of them.
   * **Submit your answers** to the exercises using [this Google form](https://forms.gle/ZnxTMvaNLweRruvp6) on **the day *before* the next class**.
   
### Questions?
* ***If you get stuck due to an error*** while running code in the lesson, [email us](mailto:hbctraining@hsph.harvard.edu) 

***

## Day 3

| Time |  Topic  | Instructor |
|:-----------:|:----------:|:--------:|
| 10:00 - 10:30 | Self-learning lessons discussion | All |
| 10:30 - 11:10 | [BANKSY Spatial Clustering](../lessons/11_banksy_clustering.qmd) | Noor |
| 11:10 - 11:15 | Break | |
| 11:15 - 11:55 | [Deconvolution](../lessons/12_deconvolution.qmd) | Will |
| 11:55 - 12:00 | Overview of self-learning materials and homework submission | Noor |

### Before the next class:

I. Please **study the contents** and **work through all the code** within the following lessons:
 
   1. [Differential Expression and Pathway Analysis](../lessons/13_dge_pathway.qmd)

      :::{.callout-note collapse="true" title="Click here for a preview of this lesson"}
      This lesson will perform differential expression analysis between celltypes of matched cancer and normal. Feed the significant genes into pathway and gene set enrichment analyses to observe trends.

      In this lesson, you will:
      
        - Run differential gene expression analysis using a Wilcox test
        - Calculate over-representated pathways
        - Identify gene set enrichment scores for pathways
      :::

   2. [Spatially Variable Genes](../lessons/14_svgs.qmd)

      :::{.callout-note collapse="true" title="Click here for a preview of this lesson"}
      This lesson will identify spatially variable genes whose expression changes across tissue locations. This lesson shows how to detect, visualize and prioritize SVGs as markers of spatial domains and gradients.
      
      In this lesson, you will:
      
        - Define the Moran’s I calculation
        - Run Moran’s I to identify spatially variable genes
        - Visualize spatialy variable genes
      :::
         
II. **Submit your work**:
   * Each lesson above contains exercises; please go through each of them.
   * **Submit your answers** to the exercises using [this Google form](https://forms.gle/9nuZirspfo2KGzSu7) on **the day *before* the next class**.
   
### Questions?
* ***If you get stuck due to an error*** while running code in the lesson, [email us](mailto:hbctraining@hsph.harvard.edu) 

***


## Day 4

| Time |  Topic  | Instructor |
|:-----------:|:----------:|:--------:|
| 10:00 - 10:30 | Self-learning lessons discussion | All |
| 10:30 - 11:30 | [Cell-Cell Communication](../lessons/15_cellchat.qmd) | Noor |
| 11:30 - 11:35 | Break | |
| 11:30 - 11:45 | Discussion, Q & A | All |
| 11:45 - 12:00 | [Wrap Up](../slides/workshop_wrapup_slides.pdf) | Will |

***

## Resources

### Other spatial transcriptomics tutorials

- [UC Davis - Advanced Topics in Single Cell RNA-Seq: Spatial Transcriptomics](https://ucdavis-bioinformatics-training.github.io/2022-December-Spatial-Transcriptomics/data_analysis/spatial_analysis)
- [Orchestrating Spatial Transcriptomics Analysis with Bioconductor
](https://lmweber.org/OSTA/)
- [SpatialData in Python](https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks.html)

### Reference papers

Here we provide papers that were used to create this workshop, in different tabsets with the associated lesson / general theme of the paper.

::: {.panel-tabset}

#### Overview of spatial transcriptomics

- *Spatial transcriptomics in health and disease* – Nature Reviews Nephrology, 2024. [Link](https://www.nature.com/articles/s41581-024-00841-1)  
- *Systematic comparison of sequencing-based spatial transcriptomic methods* – Nature Methods, 2024. [Link](https://www.nature.com/articles/s41592-024-02325-3)  
- *The spatial and single-cell landscape of skin: Charting the multiscale regulation of skin immune function* – Seminars in Immunology, 2025. [Link](https://www.sciencedirect.com/science/article/pii/S1044532325000302)  
- *Exploring tissue architecture using spatial transcriptomics* – Nature, 2021. [Link](https://www.nature.com/articles/s41586-021-03634-9)  
- *Spatial architecture of development and disease* – Nature Reviews Genetics, 2025. [Link](https://www.nature.com/articles/s41576-025-00892-5)  
- *Museum of spatial transcriptomics* – Nature Methods, 2022. [Link](https://www.nature.com/articles/s41592-022-01409-2)  
- *Spatially resolved transcriptomics: a comprehensive review of their technological advances, applications, and challenges* – Genomics, Proteomics & Bioinformatics, 2023. [Link](https://www.sciencedirect.com/science/article/pii/S1673852723000759)  
- *Standardized metrics for assessment and reproducibility of imaging-based spatial transcriptomics datasets* – Nature Biotechnology, 2025. [Link](https://www.nature.com/articles/s41587-025-02811-9)  
- *Advances in spatial transcriptomics and related data analysis strategies* – Journal of Translational Medicine, 2023. [Link](https://link.springer.com/article/10.1186/s12967-023-04150-2)  
- *What is the main bottleneck in deriving biological understanding from spatial transcriptomic profiling?* – Cell Systems, 2025. [Link](https://www.cell.com/cell-systems/fulltext/S2405-4712(25)00033-X)  

#### Dataset paper

- *High-definition spatial transcriptomic profiling of immune cell populations in colorectal cancer* – Nature Genetics, 2025. [Link](https://www.nature.com/articles/s41588-025-02193-3)  

#### Segmentation

- *Cell segmentation in imaging-based spatial transcriptomics* – Nature Biotechnology, 2021. [Link](https://www.nature.com/articles/s41587-021-01044-w)  
- *Cellpose: A generalist algorithm for cellular segmentation* – Nature Methods, 2021. [Link](https://www.nature.com/articles/s41592-020-01018-x)  

#### Normalization

- *Library size confounds biology in spatial transcriptomics data* – Genome Biology, 2024. [Link](https://link.springer.com/article/10.1186/s13059-024-03241-7)  
- *Gene count normalization in single-cell imaging-based spatially resolved transcriptomics* – Genome Biology, 2024. [Link](https://link.springer.com/article/10.1186/s13059-024-03303-w)  

#### Sketch workflow

- *Dictionary learning for integrative, multimodal and scalable single-cell analysis* – Nature Biotechnology, 2023. [Link](https://www.nature.com/articles/s41587-023-01767-y)  
- *Low-Rank Approximation and Regression in Input Sparsity Time* – Journal of the ACM, 2017. [Link](https://dl.acm.org/doi/pdf/10.1145/3019134)  

#### Dimensionality reduction

- *A comparative study of manifold learning methods for scRNA-seq with a trajectory-aware metric* – Scientific Reports, 2025. [Link](https://www.nature.com/articles/s41598-025-14301-8)  
- *Seeing data as t-SNE and UMAP do* – Nature Methods, 2024. [Link](https://www.nature.com/articles/s41592-024-02301-x)  

#### Integration

- *Fast, sensitive and accurate integration of single-cell data with Harmony* – Nature Methods, 2019. [Link](https://www.nature.com/articles/s41592-019-0619-0)  
- *Comprehensive Integration of Single-Cell Data* – Cell, 2019. [Link](https://www.cell.com/cell/fulltext/S0092-8674(19)30559-8)  

#### Clustering

- *BANKSY unifies cell typing and tissue domain segmentation for scalable spatial omics data analysis* – Nature Genetics, 2024. [Link](https://www.nature.com/articles/s41588-024-01664-3)  
- *From Louvain to Leiden: guaranteeing well-connected communities* – Scientific Reports, 2019. [Link](https://www.nature.com/articles/s41598-019-41695-z)  

#### Deconvolution

- *Spatially informed cell-type deconvolution for spatial transcriptomics* – Nature Biotechnology, 2022. [Link](https://www.nature.com/articles/s41587-022-01273-7)  

#### Spatially variable genes

- *Benchmarking algorithms for spatially variable gene identification in spatial transcriptomics* – Bioinformatics, 2025. [Link](https://academic.oup.com/bioinformatics/article/41/4/btaf131/8096371)  
- *Title not available (Categorization of computational methods to detect spatially variable genes, 2025)* – Nature Communications, 2025. [Link](https://www.nature.com/articles/s41467-025-56080-w)  

#### Cell-cell communication

- *Cell–cell communication: new insights and clinical implications* – Signal Transduction and Targeted Therapy, 2024. [Link](https://www.nature.com/articles/s41392-024-01888-z)  

#### Other methods

- *Mapping the topography of spatial gene expression with interpretable deep learning* – Nature Methods, 2025. [Link](https://www.nature.com/articles/s41592-024-02503-3)  
- *ResolVI – addressing noise and bias in spatial transcriptomics* – bioRxiv preprint, 2025. [Link](https://www.biorxiv.org/content/10.1101/2025.01.20.634005v1)  

:::